### ISSUE TITLE
运行 tiled demo 出错

### ISSUE THREAD

**Issue by MarsZone** [egret-labs/egret-game-library#13]
egret wing版本.3.0.5

[log] VillageExample
    (anonymous function) at (c:\Users\User\Desktop\egret-game-library-master\tiled\demo\index.html:130:17)
[log] Uncaught TypeError: Cannot set property 'texture' of undefined
    (anonymous function) at (c:\Users\User\Desktop\egret-game-library-master\tiled\demo\libs\modules\tiled\tiled.js:800:48)
    p.onResourceItemComp at (c:\Users\User\Desktop\egret-game-library-master\tiled\demo\libs\modules\res\res.js:3171:31)
    p.onItemComplete at (c:\Users\User\Desktop\egret-game-library-master\tiled\demo\libs\modules\res\res.js:720:31)
    p.onLoadFinish at (c:\Users\User\Desktop\egret-game-library-master\tiled\demo\libs\modules\res\res.js:1323:22)
    p.$notifyListener at (c:\Users\User\Desktop\egret-game-library-master\tiled\demo\libs\modules\egret\egret.js:550:35)
    p.dispatchEvent at (c:\Users\User\Desktop\egret-game-library-master\tiled\demo\libs\modules\egret\egret.js:529:25)
    p.dispatchEventWith at (c:\Users\User\Desktop\egret-game-library-master\tiled\demo\libs\modules\egret\egret.js:588:35)
    (anonymous function) at (c:\Users\User\Desktop\egret-game-library-master\tiled\demo\libs\modules\egret\egret.web.js:2056:26)

/**
         \* 加载图片
         \* @param $url 图片地址
         \* @version Egret 3.0.3
         */
        p.loadImage = function (url) {
            if (url == null || url == "")
                return;
            RES.getResByUrl(url, function (texture) {
                if (texture) {
                    this._sourcebitmap.texture = texture;
                    this._texture = texture;
                    this.dispatchEvent(new tiled.TMXImageLoadEvent(tiled.TMXImageLoadEvent.IMAGE_COMPLETE, texture));
                }
            }, this, RES.ResourceItem.TYPE_IMAGE);
        };

/**
         \* 加载图片
         \* @param $url 图片地址
         \* @version Egret 3.0.3
         */
        p.loadImage = function (url) {
            if (url == null || url == "")
                return;
            RES.getResByUrl(url, function (texture) {
                if (texture) {
                    this._sourcebitmap.texture = texture;
                    this._texture = texture;
                    this.dispatchEvent(new tiled.TMXImageLoadEvent(tiled.TMXImageLoadEvent.IMAGE_COMPLETE, texture));
                }
            }, this, RES.ResourceItem.TYPE_IMAGE);
        };

![2](https://cloud.githubusercontent.com/assets/3784198/15139538/36cc20d8-16c9-11e6-8e93-d631cc6d4dac.png)

![3](https://cloud.githubusercontent.com/assets/3784198/15139557/530210b4-16c9-11e6-8128-30e277b84280.png)

**Comment by MarsZone** [comment]
PS:
village.tmx的路径
image source="../../../../melonJS/examples/tiled_example_loader/data/sky.png" trans="aa6a10"/
修改为->
image source="sky.png" trans="aa6a10"/
才能打开

**Comment by bloompeony** [comment]
遇到同样问题，在`this._sourcebitmap.texture = texture;`处。
感觉不是路径的问题，因为我同样的图片，同样的路径，通过tileset+layer使用时正常。
但是在imagelayer中使用时，就会出现问题。

麻烦再进一步跟进验证、解决下~多谢！

**Comment by himuil** [comment]
已解决
