### ISSUE TITLE
导入libsrc包后 build 出错

### ISSUE THREAD

**Issue by KevinSu1991** [egret-labs/egret-game-library#25]
libs/modules/tiled/tiled.d.ts(18,18): error TS1005: 应为“=”。这个错误是怎么回事？ typescript版本不对吗？

**Comment by himuil** [comment]
最新版本库请搭配TypeScript2.1以上使用

**Comment by KevinSu1991** [comment]
{
  "_args": [
    [
      {
        "raw": "typescript@https://registry.npmjs.org/typescript/-/typescript-2.1.5-insiders.20161220.tgz",
        "scope": null,
        "escapedName": "typescript",
        "name": "typescript",
        "rawSpec": "https://registry.npmjs.org/typescript/-/typescript-2.1.5-insiders.20161220.tgz",
        "spec": "https://registry.npmjs.org/typescript/-/typescript-2.1.5-insiders.20161220.tgz",
        "type": "remote"
      },
      "/Users/apple/Documents/Egret/WingBuild/Stable_Build/egretwing-electron/extensions/typescript"
    ]
  ],
  "_from": "typescript@2.1.5-insiders.20161220",
  "_id": "typescript@2.1.5-insiders.20161220",
  "_inCache": true,
  "_location": "/typescript",
  "_phantomChildren": {},
  "_requested": {
    "raw": "typescript@https://registry.npmjs.org/typescript/-/typescript-2.1.5-insiders.20161220.tgz",
    "scope": null,
    "escapedName": "typescript",
    "name": "typescript",
    "rawSpec": "https://registry.npmjs.org/typescript/-/typescript-2.1.5-insiders.20161220.tgz",
    "spec": "https://registry.npmjs.org/typescript/-/typescript-2.1.5-insiders.20161220.tgz",
    "type": "remote"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/typescript/-/typescript-2.1.5-insiders.20161220.tgz",
  "_shasum": "a0916b27ffcb45137d227b1af1c687b1d6edcdf6",
  "_shrinkwrap": null,
  "_spec": "typescript@https://registry.npmjs.org/typescript/-/typescript-2.1.5-insiders.20161220.tgz",
  "_where": "/Users/apple/Documents/Egret/WingBuild/Stable_Build/egretwing-electron/extensions/typescript",
  "author": {
    "name": "Microsoft Corp."
  },
  "bin": {
    "tsc": "./bin/tsc",
    "tsserver": "./bin/tsserver"
  },
  "browser": {
    "buffer": false,
    "fs": false,
    "os": false,
    "path": false
  },
  "bugs": {
    "url": "https://github.com/Microsoft/TypeScript/issues"
  },
  "dependencies": {},
  "description": "TypeScript is a language for application scale JavaScript development",
  "devDependencies": {
    "@types/browserify": "latest",
    "@types/chai": "latest",
    "@types/convert-source-map": "latest",
    "@types/del": "latest",
    "@types/glob": "latest",
    "@types/gulp": "latest",
    "@types/gulp-concat": "latest",
    "@types/gulp-help": "latest",
    "@types/gulp-newer": "latest",
    "@types/gulp-sourcemaps": "latest",
    "@types/gulp-typescript": "latest",
    "@types/merge2": "latest",
    "@types/minimatch": "latest",
    "@types/minimist": "latest",
    "@types/mkdirp": "latest",
    "@types/mocha": "latest",
    "@types/node": "latest",
    "@types/q": "latest",
    "@types/run-sequence": "latest",
    "@types/through2": "latest",
    "browserify": "latest",
    "chai": "latest",
    "convert-source-map": "latest",
    "del": "latest",
    "gulp": "latest",
    "gulp-clone": "latest",
    "gulp-concat": "latest",
    "gulp-help": "latest",
    "gulp-insert": "latest",
    "gulp-newer": "latest",
    "gulp-sourcemaps": "latest",
    "gulp-typescript": "latest",
    "into-stream": "latest",
    "istanbul": "latest",
    "jake": "latest",
    "merge2": "latest",
    "minimist": "latest",
    "mkdirp": "latest",
    "mocha": "latest",
    "mocha-fivemat-progress-reporter": "latest",
    "q": "latest",
    "run-sequence": "latest",
    "sorcery": "latest",
    "through2": "latest",
    "travis-fold": "latest",
    "ts-node": "latest",
    "tslint": "4.0.0-dev.3",
    "typescript": "^2.1"
  },
  "engines": {
    "node": ">=4.2.0"
  },
  "homepage": "http://typescriptlang.org/",
  "keywords": [
    "TypeScript",
    "Microsoft",
    "compiler",
    "language",
    "javascript"
  ],
  "license": "Apache-2.0",
  "main": "./lib/typescript.js",
  "name": "typescript",
  "optionalDependencies": {},
  "readme": "[![Build Status](https://travis-ci.org/Microsoft/TypeScript.svg?branch=master)](https://travis-ci.org/Microsoft/TypeScript)\r\n[![npm version](https://badge.fury.io/js/typescript.svg)](https://www.npmjs.com/package/typescript)\r\n[![Downloads](https://img.shields.io/npm/dm/TypeScript.svg)](https://www.npmjs.com/package/typescript)\r\n\r\n# TypeScript\r\n\r\n[![Join the chat at https://gitter.im/Microsoft/TypeScript](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Microsoft/TypeScript?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)\r\n\r\n[TypeScript](http://www.typescriptlang.org/) is a language for application-scale JavaScript. TypeScript adds optional types, classes, and modules to JavaScript. TypeScript supports tools for large-scale JavaScript applications for any browser, for any host, on any OS. TypeScript compiles to readable, standards-based JavaScript. Try it out at the [playground](http://www.typescriptlang.org/Playground), and stay up to date via [our blog](https://blogs.msdn.microsoft.com/typescript) and [Twitter account](https://twitter.com/typescriptlang).\r\n\r\n## Installing\r\n\r\nFor the latest stable version:\r\n\r\n```\r\nnpm install -g typescript\r\n```\r\n\r\nFor our nightly builds:\r\n\r\n```\r\nnpm install -g typescript@next\r\n```\r\n\r\n## Contribute\r\n\r\nThere are many ways to [contribute](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md) to TypeScript.\r\n* [Submit bugs](https://github.com/Microsoft/TypeScript/issues) and help us verify fixes as they are checked in.\r\n* Review the [source code changes](https://github.com/Microsoft/TypeScript/pulls).\r\n* Engage with other TypeScript users and developers on [StackOverflow](http://stackoverflow.com/questions/tagged/typescript). \r\n* Join the [#typescript](http://twitter.com/#!/search/realtime/%23typescript) discussion on Twitter.\r\n* [Contribute bug fixes](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md).\r\n* Read the language specification ([docx](https://github.com/Microsoft/TypeScript/blob/master/doc/TypeScript%20Language%20Specification.docx?raw=true),\r\n [pdf](https://github.com/Microsoft/TypeScript/blob/master/doc/TypeScript%20Language%20Specification.pdf?raw=true), [md](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md)).\r\n\r\nThis project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see \r\nthe [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) \r\nwith any additional questions or comments.\r\n\r\n## Documentation\r\n\r\n*  [Quick tutorial](http://www.typescriptlang.org/Tutorial)\r\n*  [Programming handbook](http://www.typescriptlang.org/Handbook)\r\n*  [Language specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md)\r\n*  [Homepage](http://www.typescriptlang.org/)\r\n\r\n## Building\r\n\r\nIn order to build the TypeScript compiler, ensure that you have [Git](http://git-scm.com/downloads) and [Node.js](http://nodejs.org/) installed.\r\n\r\nClone a copy of the repo:\r\n\r\n```\r\ngit clone https://github.com/Microsoft/TypeScript.git\r\n```\r\n\r\nChange to the TypeScript directory:\r\n\r\n```\r\ncd TypeScript\r\n```\r\n\r\nInstall Gulp tools and dev dependencies:\r\n\r\n```\r\nnpm install -g gulp\r\nnpm install\r\n```\r\n\r\nUse one of the following to build and test:\r\n\r\n```\r\ngulp local            # Build the compiler into built/local \r\ngulp clean            # Delete the built compiler \r\ngulp LKG              # Replace the last known good with the built one.\r\n                      # Bootstrapping step to be executed when the built compiler reaches a stable state.\r\ngulp tests            # Build the test infrastructure using the built compiler. \r\ngulp runtests         # Run tests using the built compiler and test infrastructure. \r\n                      # You can override the host or specify a test for this command. \r\n                      # Use host=<hostName> or tests=<testPath>. \r\ngulp runtests-browser # Runs the tests using the built run.js file. Syntax is gulp runtests. Optional\r\n                        parameters 'host=', 'tests=[regex], reporter=[list|spec|json|<more>]'.\r\ngulp baseline-accept  # This replaces the baseline test results with the results obtained from gulp runtests.\r\ngulp lint             # Runs tslint on the TypeScript source.\r\ngulp help             # List the above commands. \r\n```\r\n\r\n\r\n## Usage\r\n\r\n```shell\r\nnode built/local/tsc.js hello.ts\r\n```\r\n\r\n\r\n## Roadmap\r\n\r\nFor details on our planned features and future direction please refer to our [roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap).",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Microsoft/TypeScript.git"
  },
  "scripts": {
    "build": "npm run build:compiler && npm run build:tests",
    "build:compiler": "jake local",
    "build:tests": "jake tests",
    "clean": "jake clean",
    "gulp": "gulp",
    "jake": "jake",
    "lint": "jake lint",
    "pretest": "jake tests",
    "setup-hooks": "node scripts/link-hooks.js",
    "start": "node lib/tsc",
    "test": "jake runtests-parallel"
  },
  "typings": "./lib/typescript.d.ts",
  "version": "2.1.5-insiders.20161220"
}
这是我 Egret Wing3 App下 typescript 的 package.json。 里面的版本是2.1上的吧

**Comment by himuil** [comment]
如果是最新版本的wing应该是2.1.5的了，你这个错误是在哪里报的？egret build编译报错么？

**Comment by KevinSu1991** [comment]
已经解决了 Tiled Lib版本4.0的 Wing3 3.1的引擎还不支持 把lib降到3.2.6就好了
