### ISSUE TITLE
粒子系统的getValue函数问题

### ISSUE THREAD

**Issue by jcyuan** [egret-labs/egret-game-library#26]
GravityParticleSystem里的getValue函数用于取得base-var之间的随机值。
但是为什么是取正负var值？ 是什么意图？
正确的应该是在base上叠加0至var之间的随机值吧？
否则如果lifespan = 1000, lifespanVar = 2000，那么粒子的生命最终值会是1000至-1000之间浮动。
小于0生命的粒子还有意义吗？生产了立即就被删除了。
这个是BUG还是你们本意就是这样？

**Comment by himuil** [comment]
这个就是这么设计的，所以你的随机值不要超过基础值
