### ISSUE TITLE
使用脏区域时不渲染

### ISSUE THREAD

**Issue by jcyuan** [egret-labs/egret-game-library#3]
在使用脏区域时，粒子不被渲染，因为要查脏区域的代码太复杂所以没有查具体问题所在，但是可以肯定的是只要开了脏区域，不管当前粒子发射位置在不在渲染区域内，都不会被显示。

**Comment by himuil** [comment]
最新版本的引擎已经使用了全自动脏矩形渲染，旧版设置脏区域方式将被废弃。请确认下新版是否依旧存在该问题
